[package]
name = "terminal-core"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
terminal-ansi = { path = "../terminal-ansi" }
terminal-screen = { path = "../terminal-screen" }
thiserror = { workspace = true }

metrics = { workspace = true }

[dev-dependencies]
criterion = "0.5"

[lints]
workspace = true
