[package]
name = "render-glow"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
fontdb = { workspace = true }
font8x8 = "0.3"
fontdue = "0.7"
glow = "0.13"
glutin = "0.31"
glutin-winit = "0.4"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
memmap2 = "0.9"
platform-abstraction = { path = "../platform-abstraction" }
raw-window-handle = "0.5"
render-wgpu = { path = "../render-wgpu" }
rustybuzz = "0.14"
tracing = { workspace = true }
ttf-parser = "0.25"
winit = { workspace = true }

